### ISSUE TITLE
Persona #4 - Videographer/Photographer

### ISSUE THREAD

**Issue by katz0014** [MTM6330-F18/final-SASSykatz#14]
Alexander will create a persona of a prospective student who enjoys video and photography, and interested in enrolling in the IMD program for those courses.

**Comment by brau0060** [comment]
I have completed Persona #4

**Comment by brau0060** [comment]
Fixes #14

**Comment by brau0060** [comment]
`closed`

**Comment by brau0060** [comment]
**Austin**
**21
Technology Skills medium**

Austin has just completed one year after his graduation from high school. Throughout his one year away from learning he has travailed around with his father as a assistant photographer. His father works for travel magazines. Through out the summer Austin has learned a lot about photograph and is ready to take on helping his father. Unfortunately, Austin needs a diploma in multimedia to work in this field. Austin came across the Interactive Media Design program from Algonquin College because he doesn’t only want to learn photography but also wants to learn everything else that is needed to promote your self as a designer. 

_“ I am out of high school for a year and am interested in learning about film and photography, I have worked with my dad over the summer and want to get into what he is doing. I also want to learn more than just photography and film, something that broadens my horizon in the multimedia of today. I would like to attend collage because I prefer a more hands on learning”_

The Interactive Media Design course Is exactly what Austin needs, it offers the process of web video, digital design, web development and photography, exactly what Austin wants.
