### ISSUE TITLE
Audit existing algonquin website 

### ISSUE THREAD

**Issue by katz0014** [MTM6330-F18/final-SASSykatz#19]
Look at Algonquin website and see which information is most important. Decide which information on the page we should keep. Due next Wednesday.

**Comment by pepi0039** [comment]
**Header/Banner**: Currently pretty boring. The photo is completely unrelated to the program and you can't really tell what the people in it are doing. Showing a classroom of people working or something similar would probably help illustrate things a bit better. 

Once your within the IMD page, there's sort of a dual navbar thing going on which is confusing. The info below is pertaining to the lower of the two navbars:

**Nav**: The current nav bar isn't too bad. Although, as we saw when we looked at other school's websites for similar programs - you could probably put more on less pages, so the nav could always be trimmed down a bit 

**Pages within IMD**

**School Home**

Doesn't really showcase the program, and is geared towards Media & Design as a whole - so a pretty wide gamut of programs. Not really sure how useful it is to have in there. Also, it re-directs you _out_ of the IMD section and into Media & Design, so you have to find your way back which isn't the end of the world but is frustrating. 

**Program Information**

Some useful stuff on here and I think most of the information is worth keeping. Shows the courses within the program, fees, and whatnot. 

The _Careers & Pathways_ section should probably be revamped as it's kind of useless right now. Personally, if I'm going to dedicate X amount of years and time to school, I'd love to know what kind of fields I could work in afterwards. There's a few examples but there were definitely better ones there before. 

The _Fees & Expenses_ section has some useful information, but there also seem to be too much crammed onto the page. A lot of the camera information is out of date and there's information just thrown everywhere - putting this in some kind of tabbed/drop down set up would maybe clean the page up quite a bit. Eg: Camera tab, list the cameras that you could use. Laptop tab, list the laptops/specs.

Also, adding a tab for costs for international students would probably make things a bit easier to use, too. Right now it just lists there's a premium and the amount, but this could definitely be made more user-friendly.

**Application & Admission Details**

This section is also pretty useful. There's co-op mentioned here so it should be made clear that students also have to pay $X to attend co-op and that it's longer (other programs within the Media & Design school don't have to pay to do their co-op, and it's also 6 weeks vs a semester.)

Otherwise, I think this section is mostly fine and could just use some tidying up although there's no real way to make this stuff look fun and exciting. 

**Additional Information**

I have no real idea what the purpose of this section is other than to show the coordinators contact info, but there's probably a much better spot to put that. 


**Other things that would be useful**

- Since it's a BYOD program, rather than having people click on the "BYOD" link, search their program and get to a menu that doesn't really show anything of much use. Have a section where it shows a few recommended laptops, cameras and whatever else is useful _within_ the IMD page. I personally remember when I registered but hadn't yet bought my laptop finding this a real pain to do as I was going all over the site trying to find information and sometimes winding up on outdated pages and having to navigate my way back or just starting over from scratch. 

[The FAQ tab](http://www.algonquincollege.com/mediaanddesign/program/interactive-media-design/faqs/). While there's some useful information on here, it's all very general and not overly helpful. It looks as though this wasn't updated after the program became BYOD. Also, lots of this information could be put elsewhere and save some clicks.

[Client Projects](http://www.algonquincollege.com/mediaanddesign/program/interactive-media-design/client-projects/). Seems mostly focused to people applying to do the projects, rather than students themselves.
